### PR TITLE
highest_supp_cmake_cxx_standard.cmake

### PR DESCRIPTION
**Pull request by user706**
do not fail, if a high cxx standard is not supported by the compiler

I just had the following fail: 
```bash
Target "cmTC_438fe" requires the language dialect "CXX20" , but CMake does not know the compile flags to use to enable it.
```

Now adjusted the cmake script to NOT fail, but try next lower standard (which is 17), and it worked nicely (in my setup)

### CODE REVIEW

**Comment by user706** [comment]
added another commit:

if doing:
```bash
cmake -DSSVU=ON ..
```
then `clugston_styled` must be set as include directory

**Comment by user706** [comment]
By the way: Why are cmake options for `SSVU`, `GNR`, `FOLLY` on OFF by default?
(I believe it only makes sense for `BDE` since that's the only one the clones from an external repo, via a git submodule)

**Comment by user706** [comment]
added another commit: updated folly

**Comment by jamboree** [comment]
> By the way: Why are cmake options for `SSVU`, `GNR`, `FOLLY` on OFF by default?

Some (if not all) of these fail to build in my environment, so I just leave them OFF by default.

**Pull request merged**
